# ECOMMERCE DATA ANALYSIS

In [1]:
import numpy as np
import pandas as pd

In [2]:
# upload data

In [3]:
data=pd.read_csv("online.csv")

In [5]:
# data cleaning

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   object
 2   Order Date     9800 non-null   object
 3   Ship Date      9800 non-null   object
 4   Ship Mode      9800 non-null   object
 5   Customer ID    9800 non-null   object
 6   Customer Name  9800 non-null   object
 7   Segment        9800 non-null   object
 8   Country        9800 non-null   object
 9   City           9800 non-null   object
 10  State          9800 non-null   object
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   object
 13  Product ID     9800 non-null   object
 14  Category       9800 non-null   object
 15  Sub-Category   9800 non-null   object
 16  Product Name   9800 non-null   object
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), object(15)
memory usage: 1.3+ MB

In [7]:
data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [8]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [9]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [10]:
data.tail(15)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9785,9786,CA-2016-155635,09/05/2016,13/05/2016,Standard Class,ME-17725,Max Engle,Consumer,United States,Louisville,Kentucky,40214.0,South,OFF-BI-10000962,Office Supplies,Binders,Acco Flexible ACCOHIDE Square Ring Data Binder...,48.810
9786,9787,US-2015-114377,05/11/2015,05/11/2015,Same Day,BG-11035,Barry Gonzalez,Consumer,United States,Hampton,Virginia,23666.0,South,FUR-CH-10004754,Furniture,Chairs,"Global Stack Chair with Arms, Black",149.900
9787,9788,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-BO-10001811,Furniture,Bookcases,"Atlantic Metals Mobile 5-Shelf Bookcases, Cust...",1023.332
9788,9789,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,600.558
9789,9790,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,TEC-AC-10004901,Technology,Accessories,Kensington SlimBlade Notebook Wireless Mouse w...,39.992
9790,9791,CA-2018-144491,27/03/2018,01/04/2018,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,Texas,77070.0,Central,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",211.246
9791,9792,CA-2015-127166,21/05/2015,23/05/2015,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-EN-10003134,Office Supplies,Envelopes,Staple envelope,56.064
9792,9793,CA-2015-127166,21/05/2015,23/05/2015,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,FUR-CH-10003396,Furniture,Chairs,Global Deluxe Steno Chair,107.772
9793,9794,CA-2015-127166,21/05/2015,23/05/2015,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-PA-10001560,Office Supplies,Paper,"Adams Telephone Message Books, 5 1/4” x 11”",4.832
9794,9795,CA-2015-127166,21/05/2015,23/05/2015,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,Texas,77070.0,Central,OFF-BI-10000977,Office Supplies,Binders,Ibico Plastic Spiral Binding Combs,18.240
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

In [11]:
# missing values

In [12]:
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [13]:
# postal code 05401

In [14]:
#fillna - function (numpy)

In [16]:
data['Postal Code']=data['Postal Code'].fillna('05401')

In [17]:
data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

In [19]:
data.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
dtype: int64

In [20]:
# duplicated()

In [22]:
data.duplicated().sum()

np.int64(0)

In [23]:
# otuliers

In [24]:
# outliers are the odd one out for ex if you have the marks of 50 students and the average marks is 100 but you see that only 1 student is there
# who has 400 marks so it is an outlier they are the extreme values

In [25]:
# they are not good for our analysis so we remove it

In [26]:
# we dont remove all outliers but we remove it based on our requirements

In [27]:

# Inter quartile range

In [28]:
# IOR = inter quartile range

In [29]:
# we only see outliers on numerical column

    # IQR(INER QUARTILE RANGE ) it measures the spread of data middle of data 50% it is commanly used for finding outliers
    # IQR= Q3-Q1
    #Q3 = FIRST QUARTILE (25% data 25th percentile - 25% of values are below it )
    # Q2= MEDIAN = 50 TH PERCENTILE 
    # Q3= 75TH percentile = 75 percent values are below it

# how to check outliers using IQR

In [30]:
# FIRST IQR (Q3-Q1)

# Lower bound = Q1-1.5*1OR
# UPPER BOUND = Q3+1.5*IQR

# ANY VALUE BELOW LOWER BOUND - OULIER 
# ANY VALUE ABOVE UPPER BOUND - OUTLIER

In [31]:
# EXAMPLE
# IQR= 300-200=100
#LOWER BOUND = 200-(1.5*100)
#UPPER BOUND = 300 +(1.5*100)

In [32]:
# data

In [33]:
Q1= data['Sales'].quantile(0.25)
Q3= data['Sales'].quantile(0.75)
IQR=Q3-Q1
print("Q1: ", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1:  17.248
Q3: 210.60500000000002
IQR: 193.35700000000003

In [34]:
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR
print("Lower BOUND: ", lower_bound)
print("upper bound :", upper_bound)

Lower BOUND:  -272.7875000000001
upper bound : 500.6405000000001

In [36]:
# | is the or operator

In [35]:
outliers=data[
    (data['Sales']<lower_bound)|
    (data['Sales']>upper_bound)
    ]
print(outliers)

      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class
7          8  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
10        11  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
11        12  CA-2015-115812  09/06/2015  14/06/2015  Standard Class
...      ...             ...         ...         ...             ...
9759    9760  CA-2017-146913  31/10/2017  05/11/2017  Standard Class
9774    9775  CA-2015-169019  26/07/2015  30/07/2015  Standard Class
9781    9782  CA-2017-153178  14/09/2017  18/09/2017  Standard Class
9787    9788  CA-2018-144491  27/03/2018  01/04/2018  Standard Class
9788    9789  CA-2018-144491  27/03/2018  01/04/2018  Standard Class

     Customer ID    Customer Name    Segment        Country             City  \
1       CG-12520      Claire Gute   Consumer  United States        Henderson
3       SO-20335   Sean O'Donnell   Consumer  United States  Fort Lauderdale
7       BH-11710  Brosina Hoffman   Consumer  United States      Los Angeles
10      BH-11710  Brosina Hoffman   Consumer  United States      Los Angeles
11      BH-11710  Brosina Hoffman   Consumer  United States      Los Angeles
...          ...              ...        ...            ...              ...
9759    SF-20965  Sylvia Foulston  Corporate  United States    San Francisco
9774    LF-17185      Luke Foster   Consumer  United States      San Antonio
9781    CL-12565      Clay Ludtke   Consumer  United States       Long Beach
9787    CJ-12010  Caroline Jumper   Consumer  United States          Houston
9788    CJ-12010  Caroline Jumper   Consumer  United States          Houston

           State Postal Code   Region       Product ID         Category  \
1       Kentucky     42420.0    South  FUR-CH-10000454        Furniture
3        Florida     33311.0    South  FUR-TA-10000577        Furniture
7     California     90032.0     West  TEC-PH-10002275       Technology
10    California     90032.0     West  FUR-TA-10001539        Furniture
11    California     90032.0     West  TEC-PH-10002033       Technology
...          ...         ...      ...              ...              ...
9759  California     94109.0     West  FUR-CH-10001854        Furniture
9774       Texas     78207.0  Central  OFF-BI-10004995  Office Supplies
9781    New York     11561.0     East  OFF-BI-10004390  Office Supplies
9787       Texas     77070.0  Central  FUR-BO-10001811        Furniture
9788       Texas     77070.0  Central  FUR-CH-10004063        Furniture

     Sub-Category                                       Product Name  \
1          Chairs  Hon Deluxe Fabric Upholstered Stacking Chairs,...
3          Tables      Bretford CR4500 Series Slim Rectangular Table
7          Phones                     Mitel 5320 IP Phone VoIP phone
10         Tables           Chromcraft Rectangular Conference Tables
11         Phones      Konftel 250 Conference phone - Charcoal black
...           ...                                                ...
9759       Chairs  Office Star - Professional Matrix Back Chair w...
9774      Binders          GBC DocuBind P400 Electric Binding System
9781      Binders            GBC DocuBind 200 Manual Binding Machine
9787    Bookcases  Atlantic Metals Mobile 5-Shelf Bookcases, Cust...
9788       Chairs            Global Deluxe High-Back Manager's Chair

          Sales
1      731.9400
3      957.5775
7      907.1520
10    1706.1840
11     911.4240
...         ...
9759  1403.9200
9774  2177.5840
9781   673.5680
9787  1023.3320
9788   600.5580

[1145 rows x 18 columns]

In [38]:
data.shape

(9800, 18)

# DATA ANALYSIS

In [39]:
# order by - sort_values(ascending = FLASE/TRUE)

In [40]:
# aggrgeate functions - it is applied on numerical data

In [41]:
# sum , average , min , max- numpy

In [42]:
# overall sales performance

In [43]:
total_sales=data['Sales'].sum()

In [44]:
total_sales

np.float64(2261536.7827)

In [46]:
total_Sales=data['Sales'].mean()

In [47]:
total_Sales

np.float64(230.76905945918367)

In [48]:
total_Sales=data['Sales'].max()

In [49]:
total_Sales

22638.48

In [50]:
total_Sales=data['Sales'].min()

In [51]:
total_Sales

0.444

# sales by category

In [52]:
category_Sales=data.groupby('Category')['Sales'].sum().sort_values(ascending=False)

In [53]:
category_Sales

Category
Technology         827455.8730
Furniture          728658.5757
Office Supplies    705422.3340
Name: Sales, dtype: float64

# sales by sub categry

In [54]:
sub_Sales=data.groupby('Sub-Category')['Sales'].sum().sort_values(ascending=False)

In [55]:
sub_Sales

Sub-Category
Phones         327782.4480
Chairs         322822.7310
Storage        219343.3920
Tables         202810.6280
Binders        200028.7850
Machines       189238.6310
Accessories    164186.7000
Copiers        146248.0940
Bookcases      113813.1987
Appliances     104618.4030
Furnishings     89212.0180
Paper           76828.3040
Supplies        46420.3080
Art             26705.4100
Envelopes       16128.0460
Labels          12347.7260
Fasteners        3001.9600
Name: Sales, dtype: float64

In [56]:
#TOP 10

In [58]:
sub_Sales.head(10)

Sub-Category
Phones         327782.4480
Chairs         322822.7310
Storage        219343.3920
Tables         202810.6280
Binders        200028.7850
Machines       189238.6310
Accessories    164186.7000
Copiers        146248.0940
Bookcases      113813.1987
Appliances     104618.4030
Name: Sales, dtype: float64

# sales by region

In [59]:
region_Sales=data.groupby('Region')['Sales'].sum().sort_values(ascending=False)
print(region_Sales)

Region
West       710219.6845
East       669518.7260
Central    492646.9132
South      389151.4590
Name: Sales, dtype: float64